### ISSUE TITLE
Reuse existing Watchdog route

### ISSUE THREAD

**Issue by jewzaam** [openshift/configure-alertmanager-operator#7]
For the DMS integration to work the existing receiver needs to be used (at least that's what I was able to get working).  The operator needs to look for a `route` that has the `Watchdog` alert:

```
  - receiver: "null"
    match:
      alertname: Watchdog
```

And update the `receiver` with the `webhook_config`.

This is a working confgi, URL redacted.  Duplication is because the operator also configured AM:

```
global:
  resolve_timeout: 5m
  http_config: {}
  smtp_hello: localhost
  smtp_require_tls: true
  pagerduty_url: https://events.pagerduty.com/v2/enqueue
  hipchat_api_url: https://api.hipchat.com/
  opsgenie_api_url: https://api.opsgenie.com/
  wechat_api_url: https://qyapi.weixin.qq.com/cgi-bin/
  victorops_api_url: https://alert.victorops.com/integrations/generic/20131114/alert/
route:
  receiver: "null"
  group_by:
  - job
  routes:
  - receiver: "null"
    match:
      alertname: Watchdog
    repeat_interval: 5m
  - receiver: watchdog
    match:
      alertname: Watchdog
    repeat_interval: 5m
  group_wait: 30s
  group_interval: 5m
  repeat_interval: 12h
receivers:
- name: "null"
  webhook_configs:
  - send_resolved: true
    http_config: {}
    url: https://nosnch.in/REDACTED
- name: watchdog
  webhook_configs:
  - send_resolved: true
    http_config: {}
    url: https://nosnch.in/REDACTED
templates: []
```
