### ISSUE TITLE
Prometheus showing AlertmanagerReceiversNotConfigured even Alertmanager secret is correct

### ISSUE THREAD

**Issue by kahootali** [openshift/configure-alertmanager-operator#90]
I have configured Pagerduty Operator on my management cluster & Alertmanager Operator using Hive Syncsets using the latest image i.e. `v0.1.178-762dea8`, it has created `alertmanager-main` secret in `openshift-monitoring` namespace. The Alertmanager config is valid, it has added valid Pagerduty Integration key as secret as well, I can check in Alertmanager UI in Status that config is set as well, attached below. The PD integration key is also correct but still no incidents are being reported and in Prometheus, one of the Alerts being fired is `AlertmanagerReceiversNotConfigured `, I have tried deleting Alertmanger pods as well as Promethues pods, thinking that configuration might not have been loaded. Still it is not working.

And even though I used the same config, and just replaced the PD integration key and manually applied the `alertmanager-main` secret on another cluster, it worked fine and incidents are being reported there. Alertmanager config:

```
global:
  resolve_timeout: 5m
  http_config: {}
  smtp_hello: localhost
  smtp_require_tls: true
  pagerduty_url: https://events.pagerduty.com/v2/enqueue
  hipchat_api_url: https://api.hipchat.com/
  opsgenie_api_url: https://api.opsgenie.com/
  wechat_api_url: https://qyapi.weixin.qq.com/cgi-bin/
  victorops_api_url: https://alert.victorops.com/integrations/generic/20131114/alert/
route:
  receiver: "null"
  group_by:
  - job
  routes:
  - receiver: "null"
    group_by:
    - alertname
    - severity
    continue: true
    routes:
    - receiver: "null"
      match:
        alertname: KubeQuotaExceeded
    - receiver: "null"
      match:
        alertname: UsingDeprecatedAPIAppsV1Beta1
    - receiver: "null"
      match:
        alertname: UsingDeprecatedAPIAppsV1Beta2
    - receiver: "null"
      match:
        alertname: UsingDeprecatedAPIExtensionsV1Beta1
    - receiver: "null"
      match:
        alertname: CPUThrottlingHigh
        container: registry-server
    - receiver: "null"
      match:
        alertname: CPUThrottlingHigh
        container: configmap-registry-server
    - receiver: "null"
      match:
        alertname: NodeFilesystemSpaceFillingUp
        severity: warning
    - receiver: "null"
      match:
        namespace: openshift-customer-monitoring
    - receiver: "null"
      match:
        namespace: openshift-operators
    - receiver: "null"
      match:
        alertname: SLAUptimeSRE
    - receiver: "null"
      match:
        alertname: CustomResourceDetected
    - receiver: "null"
      match:
        alertname: ImagePruningDisabled
    - receiver: "null"
      match:
        severity: info
    - receiver: make-it-warning
      match:
        alertname: KubeAPILatencyHigh
        severity: critical
    - receiver: pagerduty
      match_re:
        exported_namespace: ^default$|^kube.*|^openshift.*|^redhat-.*
    - receiver: pagerduty
      match:
        exported_namespace: ""
      match_re:
        namespace: ^default$|^kube.*|^openshift.*|^redhat-.*
    - receiver: pagerduty
      match:
        job: fluentd
    - receiver: pagerduty
      match:
        alertname: FluentdNodeDown
    - receiver: pagerduty
      match:
        cluster: elasticsearch
  group_wait: 30s
  group_interval: 5m
  repeat_interval: 12h
receivers:
- name: pagerduty
  pagerduty_configs:
  - send_resolved: true
    http_config: {}
    routing_key: <secret>
    url: https://events.pagerduty.com/v2/enqueue
    client: '{{ template "pagerduty.default.client" . }}'
    client_url: '{{ template "pagerduty.default.clientURL" . }}'
    description: '{{ .CommonLabels.alertname }} {{ .CommonLabels.severity | toUpper
      }} ({{ len .Alerts }})'
    details:
      component: '{{ .CommonLabels.alertname }}'
      firing: '{{ template "pagerduty.default.instances" .Alerts.Firing }}'
      group: '{{ .CommonLabels.alertname }}'
      link: '{{ if .CommonAnnotations.link }}{{ .CommonAnnotations.link }}{{ else
        }}https://github.com/openshift/ops-sop/tree/master/v4/alerts/{{ .CommonLabels.alertname
        }}.md{{ end }}'
      link2: '{{ if .CommonAnnotations.runbook }}{{ .CommonAnnotations.runbook }}{{
        else }}{{ end }}'
      num_firing: '{{ .Alerts.Firing | len }}'
      num_resolved: '{{ .Alerts.Resolved | len }}'
      resolved: '{{ template "pagerduty.default.instances" .Alerts.Resolved }}'
    severity: '{{ if .CommonLabels.severity }}{{ .CommonLabels.severity | toLower
      }}{{ else }}critical{{ end }}'
- name: make-it-warning
  pagerduty_configs:
  - send_resolved: true
    http_config: {}
    routing_key: <secret>
    url: https://events.pagerduty.com/v2/enqueue
    client: '{{ template "pagerduty.default.client" . }}'
    client_url: '{{ template "pagerduty.default.clientURL" . }}'
    description: '{{ .CommonLabels.alertname }} {{ .CommonLabels.severity | toUpper
      }} ({{ len .Alerts }})'
    details:
      component: '{{ .CommonLabels.alertname }}'
      firing: '{{ template "pagerduty.default.instances" .Alerts.Firing }}'
      group: '{{ .CommonLabels.alertname }}'
      link: '{{ if .CommonAnnotations.link }}{{ .CommonAnnotations.link }}{{ else
        }}https://github.com/openshift/ops-sop/tree/master/v4/alerts/{{ .CommonLabels.alertname
        }}.md{{ end }}'
      link2: '{{ if .CommonAnnotations.runbook }}{{ .CommonAnnotations.runbook }}{{
        else }}{{ end }}'
      num_firing: '{{ .Alerts.Firing | len }}'
      num_resolved: '{{ .Alerts.Resolved | len }}'
      resolved: '{{ template "pagerduty.default.instances" .Alerts.Resolved }}'
    severity: warning
- name: "null"
templates: []
```
